# Generated by Django 5.2.4 on 2025-07-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AzureOpenAIResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('endpoint', models.URLField(help_text='Base URL for the Azure OpenAI resource.')),
                ('api_key', models.CharField(max_length=255)),
                ('deployment_id', models.CharField(help_text='Name of the deployment in Azure OpenAI.', max_length=100)),
                ('api_version', models.CharField(default='2023-12-01-preview', max_length=50)),
            ],
        ),
    ]
